// 推荐视频 - 只需填入B站视频网址即可，封面和标题会自动从B站获取
window.recommendedVideos = [
    "https://www.bilibili.com/video/BV1GXuP6dEMV/",
    "https://www.bilibili.com/video/BV1yZRaBNE4W/",
    "https://www.bilibili.com/video/BV1UEVM6uEFS/",
    "https://www.bilibili.com/video/BV1SkANe8EH6/",
    "https://www.bilibili.com/video/BV1ocEr6tEX4/",
    "https://www.bilibili.com/video/BV1U4cPz5Esj/",
    "https://www.bilibili.com/video/BV1mYPLzSEEv/",
    "https://www.bilibili.com/video/BV1Vnc7zdEi2/",
    "https://www.bilibili.com/video/BV1uDc8z9E1G/",
    "https://www.bilibili.com/video/BV1JjF4z4Ehw/",
    "https://www.bilibili.com/video/BV1TtCSB8Ey2/",
    "https://www.bilibili.com/video/BV1mtCSBbEqn/",
    "https://www.bilibili.com/video/BV13nCSBNESX/",
    "https://www.bilibili.com/video/BV15yTy6iEYY/",
    "https://www.bilibili.com/video/BV1SEMn6FEUq/",
    "https://www.bilibili.com/video/BV1sRNU6tEHt/",
    "https://www.bilibili.com/video/BV1sgNZ6JEzq/",
    "https://www.bilibili.com/video/BV16Agq6wEUu/",
    "https://www.bilibili.com/video/BV1J73b6CEiy/",
    "https://www.bilibili.com/video/BV1fMuH6UEC5/",
    "https://www.bilibili.com/video/BV18neyzjEQS/",
];
