window.musicList = [
    "A Familiar Room.mp3",
    "Are You Lost (你迷失了吗).mp3",
    "As It Was.mp3",
    "Beanie.mp3",
    "Coffee.mp3",
    "Comfort Chain.mp3",
    "Flower Dance (花之舞).mp3",
    "Merry Christmas Mr.Lawrence (劳伦斯先生圣诞快乐).mp3",
    "Mice on Venus.mp3",
    "Night Stalker.mp3",
    "Slow Down.mp3",
    "Snowfall.mp3",
    "Towards the Light.mp3",
    "Track in Time (Piano Version).mp3",
    "Yhello.mp3",
    "colors.mp3",
    "her.mp3",
    "maybe (prod. lukrative & mixed matches).mp3",
    "nop.mp3",
    "this is what christmas feels like.mp3",
    "this is what losing someone feels like.mp3",
    "unhappy.mp3",
    "whoa (mind in awe).mp3",
    "丁达尔的梦.mp3",
    "夜、萤火虫和你.mp3",
    "感官过载.mp3",
    "暮春.mp3",
    "梦花.mp3",
    "降E大调夜曲, Op. 9, No. 2.mp3",
    "鸟之诗 (钢琴纯音乐).mp3",
];
