window.artists = {
    "A Familiar Room": "Aaron Cherof、Minecraft",
    "Are You Lost (你迷失了吗)": "park bird",
    "As It Was": "Harry Styles",
    "Beanie": "Chezile",
    "Coffee": "beabadoobee",
    "Comfort Chain": "Instupendo",
    "Flower Dance (花之舞)": "DJ OKAWARI",
    "Merry Christmas Mr.Lawrence (劳伦斯先生圣诞快乐)": "坂本龍一",
    "Mice on Venus": "C418",
    "Night Stalker": "Wave Saver",
    "Slow Down": "Madnap、Pauline Herr",
    "Snowfall": "Øneheart",
    "Towards the Light": "Jacoo",
    "Track in Time (Piano Version)": "Dannis Kuo",
    "降E大调夜曲, Op. 9, No. 2": "Wyatt Anderson、弗雷德里克·肖邦",
    "Yhello": "Lofive",
    "colors": "JVKE、Tilly Birds、John Mechael Howell",
    "her": "JVKE",
    "maybe (prod. lukrative & mixed matches)": "mixed matches",
    "nop": "陈越龙",
    "this is what christmas feels like": "JVKE、Forrest Frank",
    "this is what losing someone feels like": "JVKE",
    "unhappy": "s0rrow",
    "whoa (mind in awe)": "XXXTentacion",
    "丁达尔的梦": "Youzee Music",
    "夜、萤火虫和你": "AniFace",
    "感官过载": "残像音阶。M3mo",
    "暮春": "Voxa",
    "梦花": "二乘",
    "鸟之诗 (钢琴纯音乐)": "TypeD",
};